config/routes.rb
Rails.application.routes.draw do
  root 'artists#index'

  get 'search',  to: 'search#index'
  get 'suggest', to: 'search#suggest'

  resources :artists
end

app/models/album.rb
class Meta
  include Virtus.model

  attribute :rating
  attribute :have
  attribute :want
  attribute :formats
end

class Album
  include Elasticsearch::Persistence::Model

  index_name [Rails.application.engine_name, Rails.env].join('-')

  mapping _parent: { type: 'artist' } do
    indexes :suggest_title, type: 'completion', payloads: true
    indexes :suggest_track, type: 'completion', payloads: true
  end

  attribute :artist
  attribute :artist_id, String, mapping: { index: 'not_analyzed' }
  attribute :label, Hash, mapping: { type: 'object' }

  attribute :title
  attribute :suggest_title, String, default: {}, mapping: { type: 'completion', payloads: true }
  attribute :released, Date
  attribute :notes
  attribute :uri

  attribute :tracklist, Array, mapping: { type: 'object' }

  attribute :styles
  attribute :meta, Meta, mapping: { type: 'object' }
end

app/models/artist.rb
class Artist
  include Elasticsearch::Persistence::Model

  index_name [Rails.application.engine_name, Rails.env].join('-')

  analyzed_and_raw = { fields: {
    name: { type: 'string', analyzer: 'snowball' },
    raw:  { type: 'string', analyzer: 'keyword' }
  } }

  attribute :name, String, mapping: analyzed_and_raw
  attribute :suggest_name, String, default: {}, mapping: { type: 'completion', payloads: true }

  attribute :profile

  attribute :release, Date
  attribute :members, String, default: [], mapping: analyzed_and_raw
  attribute :members_combined, String, default: [], mapping: { analyzer: 'snowball' }
  attribute :suggest_member, String, default: {}, mapping: { type: 'completion', payloads: true }

  attribute :urls, String, default: []
  attribute :album_count, Integer, default: 0

  validates :name, presence: true

  def albums
    Album.search(
      { query: {
          has_parent: {
            type: 'artist',
            query: {
              filtered: {
                filter: {
                  ids: { values: [ self.id ] }
                }
              }
            }
          }
        },
        sort: 'released',
        size: 100
      },
      { type: 'album' }
  )
  end

  def to_param
    [id, name.parameterize].join('-')
  end
end

app/models/suggester.rb
class Suggester
  attr_reader :response

  def initialize(params={})
    @term = params[:term]
  end

  def response
    @response ||= begin
      Elasticsearch::Persistence.client.suggest \
      index: Artist.index_name,
      body: {
        artists: {
          text: @term,
          completion: { field: 'suggest_name' }
        },
        members: {
          text: @term,
          completion: { field: 'suggest_member' }
        },
        albums: {
          text: @term,
          completion: { field: 'suggest_title' }
        },
        tracks: {
          text: @term,
          completion: { field: 'suggest_track' }
        }
      }
    end
  end

  def as_json(options={})
    response
      .except('_shards')
      .reduce([]) do |sum,d|
        # category = { d.first => d.second.first['options'] }
        item = { :label => d.first.titleize, :value => d.second.first['options'] }
        sum << item
      end
      .reject do |d|
        d[:value].empty?
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  rescue_from Elasticsearch::Persistence::Repository::DocumentNotFound do
    render file: "public/404.html", status: 404, layout: false
  end

  def index
    @artists = Artist.all sort: 'name.raw', _source: ['name', 'album_count']
  end

  def show
    @albums = @artist.albums
  end

  def new
    @artist = Artist.new
  end

  def edit
  end

  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save refresh: true
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @artist.update(artist_params, refresh: true)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @artist.destroy refresh: true
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_artist
      @artist = Artist.find(params[:id].split('-').first)
    end

    def artist_params
      a = params.require(:artist)
      a[:members] = a[:members].split(/,\s?/) unless a[:members].is_a?(Array); a
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    tags = { pre_tags: '<em class="hl">', post_tags: '</em>' }
    @artists = Artist.search \
      query: {
        multi_match: {
          query: params[:q],
          fields: ['name^10','members^2','profile']
        }
      },
      highlight: {
        tags_schema: 'styled',
        fields: {
          name:    { number_of_fragments: 0 },
          members_combined: { number_of_fragments: 0 },
          profile: { fragment_size: 50 }
        }
      }

    @albums = Album.search \
      query: {
        multi_match: {
          query: params[:q],
          fields: ['title^100','tracklist.title^10','notes^1']
        }
      },
      highlight: {
        tags_schema: 'styled',
        fields: {
          title: { number_of_fragments: 0 },
          'tracklist.title' => { number_of_fragments: 0 },
          notes: { fragment_size: 50 }
        }
      }
  end

  def suggest
    render json: Suggester.new(params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/search_helper.rb
module SearchHelper

  def highlight(object, field)
    object.try(:hit).try(:highlight).try(field)
  end

  def highlighted(object, field)
    if h = object.try(:hit).try(:highlight).try(field).try(:first)
      h.html_safe
    else
      field.to_s.split('.').reduce(object) { |result,item| result.try(item) }
    end
  end

end

app/views/artists/_form.html.erb
<%= simple_form_for @artist do |f| %>
  <%= f.input :name %>
  <%= f.input :profile, as: :text %>
  <%= f.input :members, hint: 'Separate names by comma', input_html: { value: f.object.members.join(', ') } %>

  <%= f.button :submit %>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<header>
  <h1>
    Artists
    <%= button_to 'New Artist', new_artist_path, method: 'get', tabindex: 5 %>
  </h1>
</header>

<section id="searchbox">
<%= form_tag search_path, method: 'get' do %>
  <input type="text" name="q" value="<%= params[:q] %>" id="q" autofocus="autofocus" placeholder="start typing to search..." tabindex="0" />
<% end %>
</section>

<section class="artists">
  <% @artists.each do |artist| %>
    <%= div_for artist, class: 'result clearfix' do %>
      <h2>
        <%= link_to artist do %>
          <span class="name"><%= artist.name %></span>
          <small><%= pluralize artist.album_count, 'album' %></small>
        <% end %>
      </h2>
      <div class="actions clearfix">
        <%= button_to 'Edit', edit_artist_path(artist), method: 'get' %>
        <%= button_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
  <% end %>
</section>

<% if @artists.empty? %>
<section class="no-results">
  <p>The search hasn't returned any results...</p>
</section>
<% end %>

<script>
$.widget( "custom.suggest", $.ui.autocomplete, {
    _renderMenu: function( ul, items ) {
      $.each( items, function( index, item ) {
        var category = ul.append( "<li class='ui-autocomplete-category'>" + item.label + "</li>" );

        $.each( item.value, function( index, item ) {
          var li = $('<li class="ui-autocomplete-item"><a href="<%= Rails.application.config.relative_url_root %>'+ item.payload.url +'">'+ item.text +'</a></li>').data('ui-autocomplete-item', item )
          category.append(li)
        } )
      });
    }
  });

$( "#q" ).suggest({
  source: '<%= suggest_path %>',
  select: function(event, ui) {
    document.location.href = '<%= Rails.application.config.relative_url_root %>'+ui.item.payload.url
  }
});
</script>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<header>
  <h1>
    <span class="back"><%= link_to "〈".html_safe, artists_path, title: "Back" %></span>
    <%= @artist.name %>
    <%= button_to 'Edit', edit_artist_path(@artist), method: 'get' %>
  </h1>
</header>

<p id="notice"><%= notice %></p>

<section class="artist-info">
  <span><%= @artist.members.to_sentence last_word_connector: ' and ' %></span> |
  <span><%= pluralize @albums.size, 'album' %></span>
  <p class="artist-profile"><%= @artist.profile %></p>
</section>

<section class="albums">
  <% @albums.each do |album| %>
  <%= div_for album, class: 'clearfix' do %>
      <h3>
        <span class="title"><%= album.title %></span>
        <div class="info">
          <small><%= album.meta.formats.join(', ') %></small>
          <small><%= album.released %></small>
        </div>
      </h3>

      <div class="cover">
        <%= image_tag "http://ruby-demo-assets.s3.amazonaws.com/discogs/covers/#{album.id}.jpeg", width: '100px', class: 'cover' %>
      </div>

      <div class="content">
        <% album.tracklist.in_groups_of(album.tracklist.size/2+1).each_with_index do |half, g| %>
          <ul class=<%= cycle 'first', 'second' %> start="<%= g < 1 ? 1 : album.tracklist.size/2+2 %>">
            <% half.compact.each_with_index do |track, i| %>
              <li>
                <i class="counter"><%= g < 1 ? i+1 : i+(g*album.tracklist.size/2+2)  %></i>
                <%= track['title'] %>
                <small><%= track['duration'] %></small>
              </li>
            <% end %>
          </ul>
        <% end %>
      </div>
    <% end %>

  <% end %>

  <script>$('img').error(function(){ $(this).attr('src', '/images/blank_cover.png'); });</script>
  <script>$(document.location.hash).effect('highlight', 1500)</script>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Music</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.action_name %>">

<%= yield %>

</body>
</html>

app/views/search/index.html.erb
<header>
  <h1>
    <span class="back"><%= link_to "〈".html_safe, :back, title: "Back" %></span>
    Artists &amp; Albums
  </h1>
</header>

<section id="searchbox">
<%= form_tag search_path, method: 'get' do %>
  <input type="text" name="q" value="<%= params[:q] %>" id="q" autofocus="autofocus" placeholder="start typing to search..." tabindex="0" />
<% end %>
</section>

<section class="artists">
  <% @artists.each do |artist| %>
    <%= content_tag :div, class: 'result clearfix' do %>
      <h2>
        <%= link_to artist do %>
          <span class="name"><%= highlighted(artist, :name) %></span>
          <small><%= pluralize artist.album_count, 'album' %></small>
        <% end %>
      </h2>
      <% if highlight = highlight(artist, :members_combined) %>
      <p class="small">
        <span class="label">Members</span>
        <%= highlight.first.html_safe %>
      </p>
      <% end %>
      <% if highlight = highlight(artist, :profile) %>
      <p class="small">
        <span class="label">Profile</span>
        <%= highlight.join('&hellip;').html_safe %>
      </p>
      <% end %>
    <% end %>
  <% end %>
</section>

<section class="albums">
  <% @albums.each do |album| %>
    <%= content_tag :div, class: 'result clearfix' do %>
      <h2>
        <%= link_to artist_path(album.artist_id, anchor: "album_#{album.id}") do %>
          <span class="name"><%= highlighted(album, :title) %></span>
          <small><%= album.artist %></small>
          <small>(<%= [album.meta.formats.first, album.released].compact.join(' ') %>)</small>
        <% end %>
      </h2>

      <% if highlight = highlight(album, 'tracklist.title') %>
        <p class="small">
          <span class="label">Tracks</span>
          <%= highlight.join('&hellip;').html_safe %>
        </p>
      <% end %>

      <% if highlight = highlight(album, :notes) %>
        <p class="small">
          <span class="label">Notes</span>
          <%= highlight.map { |d| d.gsub(/^\.\s?/, '') }.join('&hellip;').html_safe %>
        </p>
      <% end %>
    <% end %>
  <% end %>
</section>

<% if @artists.empty? && @albums.empty? %>
<section class="no-results">
  <p>The search hasn't returned any results...</p>
</section>
<% end %>

<script>
$.widget( "custom.suggest", $.ui.autocomplete, {
    _renderMenu: function( ul, items ) {
      $.each( items, function( index, item ) {
        var category = ul.append( "<li class='ui-autocomplete-category'>" + item.label + "</li>" );

        $.each( item.value, function( index, item ) {
          var li = $('<li class="ui-autocomplete-item"><a href="<%= Rails.application.config.relative_url_root %>'+ item.payload.url +'">'+ item.text +'</a></li>').data('ui-autocomplete-item', item )
          category.append(li)
        } )
      });
    }
  });

$( "#q" ).suggest({
  source: '<%= suggest_path %>',
  select: function(event, ui) {
    document.location.href = '<%= Rails.application.config.relative_url_root %>'+ui.item.payload.url
  }
});
</script>